name: Daily UTC+9 Time Update

on:
  schedule:
    - cron: '0 0 * * *'  # 每天午夜UTC时间运行

jobs:
  update-time:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set execution permissions
      run: chmod +x get-utc9-time.sh

    - name: Get and update UTC+9 time
      run: ./get-utc9-time.sh

    - name: Commit changes
      run: |
        git config --local user.name "github-actions-bot"
        git config --local user.email "github-actions-bot@github.com"
        git add utc9-time.txt
        git commit -m "Update UTC+9 time" || true

    - name: Push changes
      run: |
        git push origin HEAD:$(git rev-parse --abbrev-ref HEAD)
